#!/bin/bash

SALT_VERSION=v0.17.5

wget -O - http://bootstrap.saltstack.org | sudo sh -s -- -P git $SALT_VERSION

pushd `dirname $0` > /dev/null
SCRIPT_PATH=`pwd -P`
popd > /dev/null
cp $SCRIPT_PATH/etc/salt/minion /etc/salt/minion

service salt-minion restart

# salt-call state.highstate
