#!/bin/bash
set -e

SALT_VERSION=v3004.1

wget -O - http://bootstrap.saltproject.io --no-check-certificate | sudo sh -s -- -P -x python3 git $SALT_VERSION

pushd `dirname $0` > /dev/null
SCRIPT_PATH=`pwd -P`
popd > /dev/null
cp $SCRIPT_PATH/salt/minion /etc/salt/minion

service salt-minion restart

# salt-call state.highstate
